name: gitea-s3backup-docker-build

on:
  push:
    branches:
      - 'main'

    paths-ignore:
      - "**/README.md"
      - "k8s-resources/*"
  
  pull_request:
    paths-ignore:
      - "**/README.md"
      - "k8s-resources/*"

jobs:
  buildDockerImage:
    name: Build gitea-s3backup image
    runs-on: ubuntu-latest
    steps:

      - name: Checkout source code
        # Need to use fetch-depth = 0 to fetch all tags
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: ShellCheck
        uses: ludeeus/action-shellcheck@2.0.0
        with:
          scandir: './scripts'

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v4
        with:
          images: rg.fr-par.scw.cloud/seblabcr_priv/gitea-s3backup
          tags: |
            type=sha

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          tags: ${{ steps.docker_meta.outputs.tags }}
          push: false

      - name: Add git tag 
        # Should only run when merging to main and not when triggered by pull request
        if: github.event_name != 'pull_request'
        run: |
          TAG=v$(grep -Eo  '[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+' Dockerfile)
          TAG_EXISTS=$(git tag --list $TAG)
          if [[ -z $TAG_EXISTS ]]; then
            echo "Tag $TAG does not exist. Creating new release..."
            gh release create "$TAG" --title "$TAG" --notes "Bump Gitea version to $TAG"
          else
            echo "Tag $TAG already exists. Nothing to do."
          fi
        # Setting explicitely the shell also sets options -eo pipefail to fail fast
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
